language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
script: phpunit -c app
sudo: true
before_install:
  - composer install
before_script:
  - mkdir -p build/logs
script:
  - phpunit -c app --coverage-clover build/logs/clover.xml
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php bin/coveralls -v; fi;'
